# Generated by Django 4.0.6 on 2022-08-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subelemento',
            name='id_elemento',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='id_subelemento',
        ),
        migrations.AddField(
            model_name='elemento',
            name='ele_id_elemento',
            field=models.ForeignKey(blank=True, db_column='ele_id_elemento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.elemento'),
        ),
        migrations.DeleteModel(
            name='Subelemento',
        ),
    ]
