# Generated by Django 4.0.6 on 2022-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_subelemento_id_elemento_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
