# Generated by Django 4.0.6 on 2022-08-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_ficha_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='titulo',
        ),
    ]
