# Generated by Django 4.0.6 on 2022-08-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_ficha_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
